### ISSUE TITLE
No config option for cloud without "pretty URLs"

### ISSUE THREAD

**Issue by mmigel** [dshoreman/nextshot#67]
Nextshot will not work correctly on Nextcloud instances without pretty URLs. For example - enabling these short URLs is still not possible on snap Nextcloud installations. Right now Nextshot use share links like this:
`https://example.org/s/string`

Without pretty URLs we need also "index.php" in URL, so like this:
`https://example.org/index.php/s/string`

For now, I just slightly changed the part of the script responsible for the URL, but it would be great if option for change this were also in the configuration. :)

**Comment by dshoreman** [comment]
Does it work if you set `server='https://example.org/index.php'` in your config, or does this break something? In theory that should generate the URL you need since your example shows the same string being appended in both cases.

Not to say a pretty URL option wouldn't be a bad idea, but that should at least get it working without hacks :wink:

**Comment by mmigel** [comment]
Unfortunately not, server return 405 response. :(

**Comment by dshoreman** [comment]
Hi @mmigel, sorry it's been so long! I've dug a little deeper into this now and there are a few places the Nextcloud URL is used, and a couple will need to be patched to add the `/index.php`.

I'm working on some bits now while I wait for an Ubuntu ISO to download, then I can get a basic Nextcloud instance rigged up without Pretty URLs so that I can test it out and make any further tweaks.

**Comment by dshoreman** [comment]
@mmigel This should be fixed on develop now, thanks for reporting the bug!

There are still some other things to finish before 1.4 is out, so please do reopen this issue if you try the develop branch and find it still doesn't work for you. There were some changes around Nextcloud 18 where "gallery" became "photos", but that doesn't seem to affect the link that actually gets copied so it *should* be ok.
