### ISSUE TITLE
Files without extensions don't get recognised by Nextcloud

### ISSUE THREAD

**Issue by boppy** [dshoreman/nextshot#80]
If the entered filename is not ending in dot+format (so `.png` by default), the ext should be appended, because unrecognized images will not get displayed in the webview, nor do they get a preview (`/preview` in this case just renders `[]`).

PR incoming...

**Comment by dshoreman** [comment]
Please try #82 and check that it still resolves the issues, I've updated it so that it will *always* default to the original name name.

Before, it would only do it if rename was disabled or Yad was unavailable which led to `mv Screenshots/somefile.png Screenshots/` and the error you saw.

Sorry again for nuking the original PR! I accidentally pushed `develop` instead of `boppy/develop` :facepalm:

**Comment by dshoreman** [comment]
PR merged, thanks!

If I don't find anything else to add then I'll probably release it as 1.4.4 soon
